//! A perceptual space, for anything that has to blend.
//!
//! # Why this is in the crate at all
//!
//! Because a ramp generated by mixing in linear light goes grey in the middle,
//! and a ramp generated by mixing sRGB codes goes brown. Neither is what
//! anybody wanted, and both are discovered the same way: somebody generates a
//! palette, looks at it, and starts hand-picking the midpoints. A game whose
//! whole look is procedural -- which the example game's is -- generates rather
//! than authors, so the space it generates in decides what it looks like.
//!
//! [`Oklab`] is Bjorn Ottosson's, and it is here rather than CIELAB because it
//! is closer to uniform in exactly the region a saturated palette lives in.
//!
//! # Fixed point, in three different scales, and why each one
//!
//! - The **cone responses and the axes** are [`I2F30`]: a Q30 `i32` reaching
//!   +/-2 at 9.3e-10. That is the widest scale that still holds `L` in `[0, 1]`
//!   and the two opponent axes in about +/-0.4, and its resolution is what makes
//!   the round trip through a cube root exact for every 8-bit code.
//! - The **matrix coefficients** are raw `i64` at Q30, because two of them --
//!   4.077 and -3.308 -- do not fit `I2F30`'s +/-2. They are not a colour, so they
//!   do not need a colour's type; what they need is the same scale as the
//!   values they multiply.
//! - The **hue** is an [`Angle32`], because a hue wraps and that is the
//!   workspace's type which says so. An `f32` of radians cannot be interpolated
//!   across the seam without a special case; an angle can, and its `sin_cos`
//!   and `atan2` are integer and already tested.
//!
//! # The cube root
//!
//! [`I2F30::cbrt`], which is `corvid_fixed`'s: Newton's method on `g^3 = x` from
//! a seed found by dividing the value's bit length by three. It uses nothing but multiplication, division
//! and comparison -- no `powf`, no `libm`, and no float anywhere on the path
//! from an 8-bit code to an Oklab triple and back.

use corvid_fixed::{Angle32, Factor32, I2F30, I16F16, Signed32};

use crate::LinearRgba;

/// Linear RGB to the intermediate cone responses, before the cube root. Q30.
const TO_LMS: [[i64; 3]; 3] = [
    [442_619_434, 575_882_676, 55_239_714],
    [227_529_649, 730_895_571, 115_316_604],
    [94_814_047, 302_493_299, 676_434_479],
];

/// The cube-rooted cone responses to `L`, `a`, `b`. Q30.
const LMS_TO_LAB: [[i64; 3]; 3] = [
    [225_973_536, 852_140_608, -4_372_327],
    [2_123_859_712, -2_607_681_024, 483_821_312],
    [27_814_248, 840_494_784, -868_308_992],
];

/// `L`, `a`, `b` back to the cube-rooted cone responses. Q30.
const LAB_TO_LMS: [[i64; 3]; 3] = [
    [1_073_741_824, 425_564_448, 231_717_520],
    [1_073_741_824, -113_345_632, -68_562_896],
    [1_073_741_824, -96_082_904, -1_386_722_048],
];

/// The cubed cone responses back to linear RGB. Q30.
const FROM_LMS: [[i64; 3]; 3] = [
    [4_377_368_028, -3_551_628_277, 248_002_073],
    [-1_361_974_937, 2_802_205_672, -366_488_911],
    [-4_505_513, -755_289_986, 1_833_537_324],
];

/// A colour in Oklab: one lightness and two opponent axes.
///
/// `l` runs 0 to 1 for black to white. `a` is green-to-red and `b` is
/// blue-to-yellow, both centred on zero and both reaching about +/-0.4 for the
/// most saturated colour a display can show. `alpha` is carried through
/// untouched -- it is coverage, and this space has nothing to say about it.
///
/// ```
/// use corvid_color::{Oklab, Rgba8};
/// use corvid_fixed::Factor32;
///
/// // Half way from red to green, and still a colour rather than mud.
/// let red = Oklab::from_linear(Rgba8::opaque_hex(0xFF_00_00).to_linear());
/// let green = Oklab::from_linear(Rgba8::opaque_hex(0x00_FF_00).to_linear());
/// let middle = red.lerp(green, Factor32::from_f64(0.5)).to_linear().to_srgb8();
///
/// let brightest = middle.r.max(middle.g).max(middle.b);
/// let dimmest = middle.r.min(middle.g).min(middle.b);
/// assert!(u16::from(brightest) - u16::from(dimmest) > 80, "{middle:?}");
/// ```
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "bytemuck", derive(::bytemuck::Pod, ::bytemuck::Zeroable))]
pub struct Oklab {
    /// Lightness, 0 to 1.
    pub l: I2F30,
    /// Green to red.
    pub a: I2F30,
    /// Blue to yellow.
    pub b: I2F30,
    /// Coverage, carried through untouched.
    pub alpha: I16F16,
}

impl Oklab {
    /// A colour from its three components and a coverage.
    #[must_use]
    #[inline]
    pub const fn new(l: I2F30, a: I2F30, b: I2F30, alpha: I16F16) -> Self {
        Self { l, a, b, alpha }
    }

    /// The Oklab colour a linear one denotes.
    ///
    /// A linear channel outside `[-2, 2)` -- an emissive or an HDR value, which
    /// [`LinearRgba`] has the range to hold -- saturates on the way in. Oklab
    /// describes the colours a display can show, and there is no meaningful
    /// perceptual lightness for a value forty times brighter than white.
    #[must_use]
    pub fn from_linear(rgba: LinearRgba) -> Self {
        let channels = [
            I16F16::to_i2f30(rgba.r),
            I16F16::to_i2f30(rgba.g),
            I16F16::to_i2f30(rgba.b),
        ];
        let cones = apply(TO_LMS, channels);
        let [l, a, b] = apply(LMS_TO_LAB, cones.map(I2F30::cbrt));
        Self::new(l, a, b, rgba.a)
    }

    /// The linear colour this one denotes.
    ///
    /// May land outside the unit cube: Oklab describes colours a display cannot
    /// show, and mixing two that it can occasionally passes through one that it
    /// cannot. [`LinearRgba::to_srgb8`] clamps, which is the right place for
    /// it -- a caller that wants to *know* can look at the channels first.
    #[must_use]
    pub fn to_linear(self) -> LinearRgba {
        let cones = apply(LAB_TO_LMS, [self.l, self.a, self.b]);
        let [r, g, b] = apply(FROM_LMS, cones.map(I2F30::cube));
        LinearRgba::new(
            I2F30::to_i16f16(r),
            I2F30::to_i16f16(g),
            I2F30::to_i16f16(b),
            self.alpha,
        )
    }

    /// Mixes towards `to`, perceptually.
    ///
    /// Exact at both ends, because the maths stack's `lerp`s are.
    ///
    /// This is the mix for a ramp somebody has to look at. Half way from red to
    /// green is still a colour here and is olive mud in linear light, which is
    /// the difference the whole module is for.
    #[must_use]
    #[inline]
    pub const fn lerp(self, to: Self, weight: Factor32) -> Self {
        Self::new(
            self.l.lerp(to.l, weight),
            self.a.lerp(to.a, weight),
            self.b.lerp(to.b, weight),
            self.alpha.lerp(to.alpha, weight),
        )
    }

    /// The polar form: lightness, chroma, hue.
    #[must_use]
    pub fn to_oklch(self) -> Oklch {
        let chroma = self.a.hypot(self.b);
        let hue = Angle32::atan2(i64::from(self.b.to_bits()), i64::from(self.a.to_bits()));
        Oklch::new(self.l, chroma, hue, self.alpha)
    }
}

/// A colour in Oklab's polar form: lightness, chroma, hue.
///
/// The form a palette is *generated* in, because the three axes are the three
/// decisions somebody actually makes -- how light, how saturated, and which
/// colour. A ramp of five hues at one lightness and one chroma is five lines
/// here and a hand-tuned table anywhere else.
///
/// ```
/// use corvid_color::{Oklch, Rgba8};
/// use corvid_fixed::{Angle32, I2F30};
///
/// // Five hues, evenly spaced, all equally light and equally saturated.
/// let wheel: [Rgba8; 5] = [0u32, 1, 2, 3, 4].map(|spoke| {
///     let hue = Angle32::from_turns(f64::from(spoke) / 5.0);
///     Oklch::new(I2F30::from_f64(0.7), I2F30::from_f64(0.15), hue, corvid_fixed::I16F16::ONE)
///         .to_linear()
///         .to_srgb8()
/// });
///
/// // Different colours, and none of them black or white.
/// assert_ne!(wheel[0], wheel[1]);
/// assert!(wheel.iter().all(|colour| *colour != Rgba8::BLACK));
/// ```
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "bytemuck", derive(::bytemuck::Pod, ::bytemuck::Zeroable))]
pub struct Oklch {
    /// Lightness, 0 to 1.
    pub l: I2F30,
    /// Chroma: how far from grey, reaching about 0.4.
    pub c: I2F30,
    /// Hue.
    ///
    /// An [`Angle32`] rather than a pair of axes, because a hue wraps and this
    /// is the workspace's type that says so -- and because the trigonometry that
    /// crosses to and from [`Oklab`] is integer, so there is no float on the
    /// path either way.
    pub h: Angle32,
    /// Coverage, carried through untouched.
    pub alpha: I16F16,
}

impl Oklch {
    /// A colour from its three components and a coverage.
    #[must_use]
    #[inline]
    pub const fn new(l: I2F30, c: I2F30, h: Angle32, alpha: I16F16) -> Self {
        Self { l, c, h, alpha }
    }

    /// The polar form of a Cartesian one.
    #[must_use]
    #[inline]
    pub fn from_oklab(lab: Oklab) -> Self {
        lab.to_oklch()
    }

    /// The Cartesian form of this one.
    #[must_use]
    pub fn to_oklab(self) -> Oklab {
        let (sine, cosine) = self.h.sin_cos();
        let component = |unit: Signed32| self.c.saturating_mul_signed32(unit);
        Oklab::new(self.l, component(cosine), component(sine), self.alpha)
    }

    /// The linear colour this one denotes.
    #[must_use]
    pub fn to_linear(self) -> LinearRgba {
        self.to_oklab().to_linear()
    }

    /// The Oklch colour a linear one denotes.
    #[must_use]
    pub fn from_linear(rgba: LinearRgba) -> Self {
        Oklab::from_linear(rgba).to_oklch()
    }
}

impl From<Oklab> for Oklch {
    #[inline]
    fn from(lab: Oklab) -> Self {
        lab.to_oklch()
    }
}

impl From<Oklch> for Oklab {
    #[inline]
    fn from(lch: Oklch) -> Self {
        lch.to_oklab()
    }
}

/// A Q30 3x3 matrix applied to a Q30 triple.
///
/// One [`I2F30::dot_q30`] per row. The coefficients stay raw `i64` at Q30
/// because two of them -- 4.077 and -3.308 -- are outside `I2F30`'s `+/-2`, and
/// that operation takes them at that scale for exactly this reason.
#[must_use]
fn apply(matrix: [[i64; 3]; 3], vector: [I2F30; 3]) -> [I2F30; 3] {
    matrix.map(|row| I2F30::dot_q30(row, vector))
}
