//! A perceptual space, for anything that has to blend.
//!
//! # Why this is in the crate at all
//!
//! Because a ramp generated by mixing in linear light goes grey in the middle,
//! and a ramp generated by mixing sRGB codes goes brown. Neither is what
//! anybody wanted, and both are discovered the same way: somebody generates a
//! palette, looks at it, and starts hand-picking the midpoints. A game whose
//! whole look is procedural — which the example game's is — generates rather
//! than authors, so the space it generates in decides what it looks like.
//!
//! [`Oklab`] is Björn Ottosson's, and it is here rather than CIELAB because it
//! is closer to uniform in exactly the region a saturated palette lives in.
//!
//! # Fixed point, in three different scales, and why each one
//!
//! - The **cone responses and the axes** are [`I2F30`]: a Q30 `i32` reaching
//!   ±2 at 9.3e-10. That is the widest scale that still holds `L` in `[0, 1]`
//!   and the two opponent axes in about ±0.4, and its resolution is what makes
//!   the round trip through a cube root exact for every 8-bit code.
//! - The **matrix coefficients** are raw `i64` at Q30, because two of them —
//!   4.077 and −3.308 — do not fit `I2F30`'s ±2. They are not a colour, so they
//!   do not need a colour's type; what they need is the same scale as the
//!   values they multiply.
//! - The **hue** is an [`Angle32`], because a hue wraps and that is the
//!   workspace's type which says so. An `f32` of radians cannot be interpolated
//!   across the seam without a special case; an angle can, and its `sin_cos`
//!   and `atan2` are integer and already tested.
//!
//! # The cube root
//!
//! Newton's method on `g³ = x`, in `i128`, from a seed found by dividing the
//! value's bit length by three. It uses nothing but multiplication, division
//! and comparison — no `powf`, no `libm`, and no float anywhere on the path
//! from an 8-bit code to an Oklab triple and back.

use corvid_fixed::{Angle32, Factor32, I2F30, I16F16, Signed32};

use crate::LinearRgba;

/// Linear RGB to the intermediate cone responses, before the cube root. Q30.
const TO_LMS: [[i64; 3]; 3] = [
    [442_619_434, 575_882_676, 55_239_714],
    [227_529_649, 730_895_571, 115_316_604],
    [94_814_047, 302_493_299, 676_434_479],
];

/// The cube-rooted cone responses to `L`, `a`, `b`. Q30.
const LMS_TO_LAB: [[i64; 3]; 3] = [
    [225_973_536, 852_140_608, -4_372_327],
    [2_123_859_712, -2_607_681_024, 483_821_312],
    [27_814_248, 840_494_784, -868_308_992],
];

/// `L`, `a`, `b` back to the cube-rooted cone responses. Q30.
const LAB_TO_LMS: [[i64; 3]; 3] = [
    [1_073_741_824, 425_564_448, 231_717_520],
    [1_073_741_824, -113_345_632, -68_562_896],
    [1_073_741_824, -96_082_904, -1_386_722_048],
];

/// The cubed cone responses back to linear RGB. Q30.
const FROM_LMS: [[i64; 3]; 3] = [
    [4_377_368_028, -3_551_628_277, 248_002_073],
    [-1_361_974_937, 2_802_205_672, -366_488_911],
    [-4_505_513, -755_289_986, 1_833_537_324],
];

/// One, at the scale the cone responses and the axes are held in.
const ONE_Q30: i128 = 1 << 30;

/// One, at the scale a [`Signed32`] holds. Not a power of two, which is why
/// every crossing divides by it rather than shifting.
const UNIT: i128 = i32::MAX as i128;

/// A colour in Oklab: one lightness and two opponent axes.
///
/// `l` runs 0 to 1 for black to white. `a` is green-to-red and `b` is
/// blue-to-yellow, both centred on zero and both reaching about ±0.4 for the
/// most saturated colour a display can show. `alpha` is carried through
/// untouched — it is coverage, and this space has nothing to say about it.
///
/// ```
/// use corvid_color::{Oklab, Rgba8};
/// use corvid_fixed::Factor32;
///
/// // Half way from red to green, and still a colour rather than mud.
/// let red = Oklab::from_linear(Rgba8::opaque_hex(0xFF_00_00).to_linear());
/// let green = Oklab::from_linear(Rgba8::opaque_hex(0x00_FF_00).to_linear());
/// let middle = red.lerp(green, Factor32::from_f64(0.5)).to_linear().to_srgb8();
///
/// let brightest = middle.r.max(middle.g).max(middle.b);
/// let dimmest = middle.r.min(middle.g).min(middle.b);
/// assert!(u16::from(brightest) - u16::from(dimmest) > 80, "{middle:?}");
/// ```
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "bytemuck", derive(::bytemuck::Pod, ::bytemuck::Zeroable))]
pub struct Oklab {
    /// Lightness, 0 to 1.
    pub l: I2F30,
    /// Green to red.
    pub a: I2F30,
    /// Blue to yellow.
    pub b: I2F30,
    /// Coverage, carried through untouched.
    pub alpha: I16F16,
}

impl Oklab {
    /// A colour from its three components and a coverage.
    #[must_use]
    #[inline]
    pub const fn new(l: I2F30, a: I2F30, b: I2F30, alpha: I16F16) -> Self {
        Self { l, a, b, alpha }
    }

    /// The Oklab colour a linear one denotes.
    ///
    /// A linear channel outside `[-2, 2)` — an emissive or an HDR value, which
    /// [`LinearRgba`] has the range to hold — saturates on the way in. Oklab
    /// describes the colours a display can show, and there is no meaningful
    /// perceptual lightness for a value forty times brighter than white.
    #[must_use]
    pub fn from_linear(rgba: LinearRgba) -> Self {
        let channels = [
            narrow_channel(rgba.r),
            narrow_channel(rgba.g),
            narrow_channel(rgba.b),
        ];
        let cones = apply(TO_LMS, channels);
        let [l, a, b] = apply(LMS_TO_LAB, cones.map(cbrt));
        Self::new(l, a, b, rgba.a)
    }

    /// The linear colour this one denotes.
    ///
    /// May land outside the unit cube: Oklab describes colours a display cannot
    /// show, and mixing two that it can occasionally passes through one that it
    /// cannot. [`LinearRgba::to_srgb8`] clamps, which is the right place for
    /// it — a caller that wants to *know* can look at the channels first.
    #[must_use]
    pub fn to_linear(self) -> LinearRgba {
        let cones = apply(LAB_TO_LMS, [self.l, self.a, self.b]);
        let [r, g, b] = apply(FROM_LMS, cones.map(cube));
        LinearRgba::new(widen(r), widen(g), widen(b), self.alpha)
    }

    /// Mixes towards `to`, perceptually.
    ///
    /// Exact at both ends, because the maths stack's `lerp`s are.
    ///
    /// This is the mix for a ramp somebody has to look at. Half way from red to
    /// green is still a colour here and is olive mud in linear light, which is
    /// the difference the whole module is for.
    #[must_use]
    #[inline]
    pub const fn lerp(self, to: Self, weight: Factor32) -> Self {
        Self::new(
            self.l.lerp(to.l, weight),
            self.a.lerp(to.a, weight),
            self.b.lerp(to.b, weight),
            self.alpha.lerp(to.alpha, weight),
        )
    }

    /// The polar form: lightness, chroma, hue.
    #[must_use]
    pub fn to_oklch(self) -> Oklch {
        let chroma = self.a.hypot(self.b);
        let hue = Angle32::atan2(i64::from(self.b.to_bits()), i64::from(self.a.to_bits()));
        Oklch::new(self.l, chroma, hue, self.alpha)
    }
}

/// A colour in Oklab's polar form: lightness, chroma, hue.
///
/// The form a palette is *generated* in, because the three axes are the three
/// decisions somebody actually makes — how light, how saturated, and which
/// colour. A ramp of five hues at one lightness and one chroma is five lines
/// here and a hand-tuned table anywhere else.
///
/// ```
/// use corvid_color::{Oklch, Rgba8};
/// use corvid_fixed::{Angle32, I2F30};
///
/// // Five hues, evenly spaced, all equally light and equally saturated.
/// let wheel: [Rgba8; 5] = [0u32, 1, 2, 3, 4].map(|spoke| {
///     let hue = Angle32::from_turns(f64::from(spoke) / 5.0);
///     Oklch::new(I2F30::from_f64(0.7), I2F30::from_f64(0.15), hue, corvid_fixed::I16F16::ONE)
///         .to_linear()
///         .to_srgb8()
/// });
///
/// // Different colours, and none of them black or white.
/// assert_ne!(wheel[0], wheel[1]);
/// assert!(wheel.iter().all(|colour| *colour != Rgba8::BLACK));
/// ```
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "bytemuck", derive(::bytemuck::Pod, ::bytemuck::Zeroable))]
pub struct Oklch {
    /// Lightness, 0 to 1.
    pub l: I2F30,
    /// Chroma: how far from grey, reaching about 0.4.
    pub c: I2F30,
    /// Hue.
    ///
    /// An [`Angle32`] rather than a pair of axes, because a hue wraps and this
    /// is the workspace's type that says so — and because the trigonometry that
    /// crosses to and from [`Oklab`] is integer, so there is no float on the
    /// path either way.
    pub h: Angle32,
    /// Coverage, carried through untouched.
    pub alpha: I16F16,
}

impl Oklch {
    /// A colour from its three components and a coverage.
    #[must_use]
    #[inline]
    pub const fn new(l: I2F30, c: I2F30, h: Angle32, alpha: I16F16) -> Self {
        Self { l, c, h, alpha }
    }

    /// The polar form of a Cartesian one.
    #[must_use]
    #[inline]
    pub fn from_oklab(lab: Oklab) -> Self {
        lab.to_oklch()
    }

    /// The Cartesian form of this one.
    #[must_use]
    pub fn to_oklab(self) -> Oklab {
        let (sine, cosine) = self.h.sin_cos();
        let chroma = i128::from(self.c.to_bits());
        let component = |unit: Signed32| {
            I2F30::from_bits(narrow_q30(divide(
                chroma * i128::from(unit.to_bits()),
                UNIT,
            )))
        };
        Oklab::new(self.l, component(cosine), component(sine), self.alpha)
    }

    /// The linear colour this one denotes.
    #[must_use]
    pub fn to_linear(self) -> LinearRgba {
        self.to_oklab().to_linear()
    }

    /// The Oklch colour a linear one denotes.
    #[must_use]
    pub fn from_linear(rgba: LinearRgba) -> Self {
        Oklab::from_linear(rgba).to_oklch()
    }
}

impl From<Oklab> for Oklch {
    #[inline]
    fn from(lab: Oklab) -> Self {
        lab.to_oklch()
    }
}

impl From<Oklch> for Oklab {
    #[inline]
    fn from(lch: Oklch) -> Self {
        lch.to_oklab()
    }
}

/// A Q30 3×3 matrix applied to a Q30 triple, accumulated wide.
///
/// The coefficients reach 4.08, so a Q30 coefficient times a Q30 value is a Q60
/// product near 2⁶² and three of them summed do not fit an `i64` — the same
/// bound `corvid_shape::project` accumulates wide for, and for the same reason.
#[must_use]
fn apply(matrix: [[i64; 3]; 3], vector: [I2F30; 3]) -> [I2F30; 3] {
    let [x, y, z] = vector.map(|value| i128::from(value.to_bits()));
    matrix.map(|row| {
        let sum = i128::from(row[0]) * x + i128::from(row[1]) * y + i128::from(row[2]) * z;
        I2F30::from_bits(narrow_q30(divide(sum, ONE_Q30)))
    })
}

/// The real cube root, in Q30.
///
/// Newton's method on `g³ = x`, worked on the bit patterns in `i128` so that
/// nothing rounds through a narrower type on the way. The seed divides the
/// value's bit length by three, which lands within about 25%; Newton roughly
/// squares the accuracy each pass, so seven passes reach the last bit with room
/// to spare. `tests/oklab.rs` checks that by round-tripping every 8-bit code on
/// all three channels rather than by trusting the argument.
///
/// Signed, because a cone response is negative for a colour outside the gamut
/// and Oklab's own definition takes the signed root.
#[must_use]
fn cbrt(value: I2F30) -> I2F30 {
    let bits = i128::from(value.to_bits());
    if bits == 0 {
        return I2F30::ZERO;
    }
    let negative = bits < 0;
    let magnitude = bits.unsigned_abs().cast_signed();

    // Solving `g³ = x` in Q30 means solving `g³ = bits · 2⁶⁰` on the patterns.
    let target = magnitude << 60;

    // Seed: a bit length of `n` means the value is about `2^(n-1)`, so its cube
    // root is about `2^((n-1)/3)`.
    let length = corvid_bits::magnitude_bits_i128(target);
    let mut guess: i128 = 1 << (length.saturating_sub(1) / 3);

    let mut pass = 0;
    while pass < 7 {
        let square = guess * guess;
        if square == 0 {
            break;
        }
        guess = (2 * guess + target / square) / 3;
        pass += 1;
    }

    let root = narrow_q30(guess);
    I2F30::from_bits(if negative { -root } else { root })
}

/// The cube, in Q30.
///
/// The inverse of [`cbrt`], and the other half of the round trip that
/// `tests/oklab.rs` measures.
#[must_use]
fn cube(value: I2F30) -> I2F30 {
    let bits = i128::from(value.to_bits());
    I2F30::from_bits(narrow_q30(divide(bits * bits * bits, ONE_Q30 * ONE_Q30)))
}

/// An `I16F16` linear channel as the `I2F30` a cone response is held in.
///
/// Saturating, because `I16F16` reaches 32 768 and `I2F30` stops at 2. See
/// [`Oklab::from_linear`] for why that is the right answer rather than a lost
/// value.
#[must_use]
#[inline]
fn narrow_channel(value: I16F16) -> I2F30 {
    I2F30::from_bits(narrow_q30(i128::from(value.to_bits()) << 14))
}

/// An `I2F30` cone response back to the `I16F16` a linear channel is.
#[must_use]
#[inline]
fn widen(value: I2F30) -> I16F16 {
    I16F16::from_bits(narrow_i32(divide(i128::from(value.to_bits()), 1 << 14)))
}

/// A quotient, rounded to nearest with halves away from zero.
///
/// Rust's integer division truncates towards zero, which turns every sub-unit
/// shortfall into a whole step in the last place, in the same direction every
/// time. Every scaling here goes through this instead.
#[must_use]
#[inline]
const fn divide(numerator: i128, denominator: i128) -> i128 {
    // `unsigned_abs` rather than `abs`, which overflows on `i128::MIN` — a
    // value no call site here can reach, and a panic the workspace forbids
    // being one branch away from is not worth the shorter spelling.
    let half = (denominator.unsigned_abs() / 2).cast_signed();
    let bump = if numerator < 0 { -half } else { half };
    (numerator + bump) / denominator
}

/// A wide value brought back to an `I2F30` pattern, clamping rather than
/// wrapping.
#[must_use]
#[inline]
const fn narrow_q30(value: i128) -> i32 {
    narrow_i32(value)
}

/// A wide value brought back to an `i32`, clamping rather than wrapping.
#[must_use]
#[inline]
#[expect(
    clippy::cast_possible_truncation,
    reason = "the value is clamped to i32's range on the two lines above the cast, which is what makes the narrowing exact"
)]
const fn narrow_i32(value: i128) -> i32 {
    if value > i32::MAX as i128 {
        i32::MAX
    } else if value < i32::MIN as i128 {
        i32::MIN
    } else {
        value as i32
    }
}
