//! Conversions between the signed normalized widths.
//!
//! All three types denote the same range -- `-1.0 ..= 1.0` -- and differ only
//! in how finely they cut it, so unlike the fixed-point conversions next door
//! none of these can be out of range. Widening is exact and narrowing rounds,
//! which is the whole of what there is to say about them.
//!
//! They are here rather than generated by
//! [`define_signed`](super::macros::define_signed) because a conversion names
//! two types and that macro knows one.

use super::{Signed8, Signed16, Signed32};

/// Rescales a bit pattern from one signed normalized width to another.
///
/// `from` and `to` are the two types' `MAX` patterns. The quotient is rounded
/// half away from zero, which is what every other rounding in this crate does,
/// and the widening is what keeps the product exact before it.
#[inline]
const fn rescale(bits: i32, from: i32, to: i32) -> i32 {
    let numerator = bits as i64 * to as i64;
    let half = from as i64 / 2;
    let bump = if numerator < 0 { -half } else { half };
    ((numerator + bump) / from as i64) as i32
}

impl Signed8 {
    /// The same value at sixteen bits. Exact.
    ///
    /// ```
    /// use corvid_fixed::{Signed8, Signed16};
    ///
    /// assert_eq!(Signed8::MAX.to_signed16(), Signed16::MAX);
    /// assert_eq!(Signed8::MIN.to_signed16(), Signed16::MIN);
    /// assert_eq!(Signed8::ZERO.to_signed16(), Signed16::ZERO);
    /// ```
    #[must_use]
    #[inline]
    pub const fn to_signed16(self) -> Signed16 {
        Signed16::from_bits(rescale(
            self.canonicalize().to_bits() as i32,
            i8::MAX as i32,
            i16::MAX as i32,
        ) as i16)
    }

    /// The same value at thirty-two bits. Exact.
    #[must_use]
    #[inline]
    pub const fn to_signed32(self) -> Signed32 {
        Signed32::from_bits(rescale(
            self.canonicalize().to_bits() as i32,
            i8::MAX as i32,
            i32::MAX,
        ))
    }
}

impl Signed16 {
    /// The same value at eight bits, rounded to nearest.
    #[must_use]
    #[inline]
    pub const fn to_signed8(self) -> Signed8 {
        Signed8::from_bits(rescale(
            self.canonicalize().to_bits() as i32,
            i16::MAX as i32,
            i8::MAX as i32,
        ) as i8)
    }

    /// The same value at thirty-two bits. Exact.
    #[must_use]
    #[inline]
    pub const fn to_signed32(self) -> Signed32 {
        Signed32::from_bits(rescale(
            self.canonicalize().to_bits() as i32,
            i16::MAX as i32,
            i32::MAX,
        ))
    }
}

impl Signed32 {
    /// The same value at sixteen bits, rounded to nearest.
    ///
    /// The narrowing a sine or a cosine takes on the way to something stored at
    /// sixteen bits -- a mesh vertex, a screen position. Sixteen of the
    /// thirty-two bits go, so this is a rounding rather than a conversion, and
    /// the ends survive it exactly: `MAX` is `MAX` and `MIN` is `MIN`, which is
    /// what stops a full deflection coming back as one step short of one.
    ///
    /// ```
    /// use corvid_fixed::{Signed16, Signed32};
    ///
    /// assert_eq!(Signed32::MAX.to_signed16(), Signed16::MAX);
    /// assert_eq!(Signed32::MIN.to_signed16(), Signed16::MIN);
    /// assert_eq!(Signed32::ZERO.to_signed16(), Signed16::ZERO);
    ///
    /// // Halfway rounds away from zero, as everywhere else here.
    /// let half = Signed32::from_f64(0.5);
    /// assert_eq!(half.to_signed16(), Signed16::from_f64(0.5));
    /// ```
    #[must_use]
    #[inline]
    pub const fn to_signed16(self) -> Signed16 {
        Signed16::from_bits(
            rescale(self.canonicalize().to_bits(), i32::MAX, i16::MAX as i32) as i16,
        )
    }

    /// The same value at eight bits, rounded to nearest.
    #[must_use]
    #[inline]
    pub const fn to_signed8(self) -> Signed8 {
        Signed8::from_bits(rescale(self.canonicalize().to_bits(), i32::MAX, i8::MAX as i32) as i8)
    }
}
